version: "3.9"
services:
  api:
    build: .
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    command: >
      sh -c "prisma generate &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
